#!/usr/bin/env python3
"""build_gapstream.py -- generate a targeted 8u patch-scan script from missing_data.txt.

Reads the gap report (tools/build_heightmap.py writes it) and emits GapStream.lua: a GroundStream variant
that visits ONLY the missing cells. Per gap segment it scans a mini-raster at 8u -- two z-lines (cell centre
-4/+4) with 8u x-steps -- so every missing 16u cell gets 4 sample opportunities. Between segments the camera
walks hop-by-hop exactly like GroundStream (never a far jump), with the same zero-hold streaming guard.

Segments are padded one cell each side and near-neighbours merged, rows ordered bottom-up with alternating
sweep direction; at runtime each segment is entered from whichever end is closer.

Run:  python tools/build_gapstream.py [--deploy]
  writes ingame/GapStream.lua; --deploy also copies it into the game's scripts/OnKey/.
Key: F8 (add "GapStream.lua=f8" under [OnKey]). Press again to abort.
"""
import re, pathlib, argparse, shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAPS = ROOT / "missing_data.txt"
OUT = ROOT / "ingame" / "GapStream.lua"
GAME_ONKEY = pathlib.Path(r"C:\Games\Mercenaries 2 World in Flames\scripts\OnKey")

PAD = 16          # extend each segment one 16u cell each side (guaranteed overlap with good data)
MERGE_GAP = 96    # merge segments in the same row closer than this (transit costs more than scanning)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deploy", action="store_true", help="also copy GapStream.lua into the game's OnKey folder")
    args = ap.parse_args()

    rows = {}   # z -> [(x0, x1), ...]
    for line in GAPS.read_text(encoding="utf-8").splitlines():
        m = re.match(r"z=(-?\d+)\s+(.*)", line)
        if not m:
            continue
        z = int(m.group(1))
        spans = [(int(a), int(b)) for a, b in re.findall(r"x\[(-?\d+)\.\.(-?\d+)\]", m.group(2))]
        if spans:
            rows.setdefault(z, []).extend(spans)

    if not rows:
        raise SystemExit("[gapstream] no gaps in %s -- nothing to generate" % GAPS)

    segs = []
    for z in sorted(rows):                          # bottom-up like the main scan
        spans = sorted((a - PAD, b + PAD) for a, b in rows[z])
        merged = [list(spans[0])]
        for a, b in spans[1:]:
            if a - merged[-1][1] <= MERGE_GAP:
                merged[-1][1] = max(merged[-1][1], b)
            else:
                merged.append([a, b])
        segs.extend((z, a, b) for a, b in merged)

    cells = sum((b - a) // 8 * 2 for _, a, b in segs)
    lua_segs = ",\n    ".join("{z=%d,x0=%d,x1=%d}" % s for s in segs)

    lua = LUA_TEMPLATE.replace("@@SEGS@@", lua_segs).replace("@@NSEG@@", str(len(segs))).replace("@@NPTS@@", str(cells))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(lua, encoding="ascii")
    print("[gapstream] %d gap segment(s) across %d row(s), ~%d probe points -> %s"
          % (len(segs), len(rows), cells, OUT))
    if args.deploy:
        shutil.copy(OUT, GAME_ONKEY / "GapStream.lua")
        print("[gapstream] deployed to %s (add \"GapStream.lua=f8\" under [OnKey])" % GAME_ONKEY)


LUA_TEMPLATE = r'''local KEYVAL = "f8"   -- toggle key (add "GapStream.lua=f8" under [OnKey]); press again to ABORT

-- GapStream.lua -- GENERATED by mercs2-webmap tools/build_gapstream.py from missing_data.txt. Do not
-- hand-edit (regenerate after each rebuild). Targeted 8u patch scan: visits @@NSEG@@ gap segment(s) left
-- behind by the full-map pass and re-probes each as a 2-line 8u mini-raster (4 chances per missing 16u
-- cell). Same safety model as GroundStream: cinematic-camera prop probe, hop-by-hop transit between
-- segments (never a far jump), exact-0 readings held as "unstreamed" and retried, F8 aborts + restores.

local Ess = _G.Ess
if not (Ess and Ess.Camera and Ess.Player and Ess.Loop and Ess.Object) then
    if Loader and Loader.Printf then Loader.Printf("[gapstream] load Ess (dist/Ess.lua) first") end
    return
end

local LOOP_ID = "GapStream"
local RES = 8                          -- sample step inside a segment (8u = quarter-cell)
local HOP = 16                         -- transit hop between segments
local TEMPLATE = "Verification Camera"
local CLEAR, CAM_UP = 100, 40
local SENTINEL_H = 350
local SEARCH, MAX_RETRY = 90, 14
local GUESS_LO, GUESS_HI = -200, 700
local DT = 0.03
local ZERO_RETRY = MAX_RETRY * 4

local SEGS = {
    @@SEGS@@
}

local function wsline(s) if Loader and Loader.WsSend then pcall(Loader.WsSend, s) end end
local function clamp(v, lo, hi) if v < lo then return lo elseif v > hi then return hi else return v end end

_G.GapStream = _G.GapStream or { on = false, n = 0, prop = nil }
local S = _G.GapStream

local function restore()
    pcall(Ess.Camera.endCinematic, 0)
    if S.prop and Ess.Object.valid(S.prop) then pcall(Object.Remove, S.prop) end
    S.prop = nil
end

if S.on then
    S.on = false; Ess.Loop.stop(LOOP_ID); restore()
    wsline("<<ROADLOG>>STOP " .. (S.n or 0))
    Ess.Log(string.format("[gapstream] aborted -- %d point(s). Camera restored.", S.n or 0)); return
end

local px, py, pz = Ess.Player.pose(0)
if not px then Ess.Log("[gapstream] no player character"); return end

S.prop = Ess.Object.spawn(TEMPLATE, px, py, pz, 0)
if not (S.prop and Ess.Object.valid(S.prop)) then Ess.Log("[gapstream] couldn't spawn '" .. TEMPLATE .. "'"); return end
pcall(Object.DisablePhysics, S.prop)
pcall(Ess.Camera.beginCinematic, 0, 0)
pcall(Ess.Camera.lookAtObject, S.prop, nil, 0)

S.on, S.n, S.guess, S.retry, S.zeroStreak = true, 0, py or 0, 0, 0
S.seg = 1                                        -- current segment index
S.phase = "transit"                              -- transit -> scan -> (next seg) ... -> done
S.tx, S.tz = px, pz                              -- transit cursor
S.line, S.li = 1, 0                              -- scan cursor: line 1 (z-4) / 2 (z+4), step index
wsline("<<ROADLOG>>START")
Ess.Log(string.format("[gapstream] PATCH: %d segment(s), ~@@NPTS@@ probe pts at %du. Walks between gaps. F8 aborts.",
    #SEGS, RES))

local function segEntry(seg)                     -- enter from whichever end is closer to the camera
    local d0 = math.abs(S.tx - seg.x0) + math.abs(S.tz - seg.z)
    local d1 = math.abs(S.tx - seg.x1) + math.abs(S.tz - seg.z)
    if d1 < d0 then return seg.x1, -1 else return seg.x0, 1 end
end

Ess.Loop.start(LOOP_ID, DT, function()
    if not S.on then return false end
    local seg = SEGS[S.seg]
    if not seg then
        S.on = false; restore(); wsline("<<ROADLOG>>STOP " .. S.n)
        Ess.Log(string.format("[gapstream] DONE -- %d patch point(s). Camera restored.", S.n))
        return false
    end

    -- pick this tick's probe point
    local x, z
    if S.phase == "transit" then
        x, z = S.tx, S.tz
    else
        local steps = math.floor((seg.x1 - seg.x0) / RES)
        if S.li > steps then                     -- line finished
            if S.line == 1 then S.line, S.li = 2, 0; S.dir = -S.dir   -- serpentine: line 2 sweeps back
            else                                  -- segment finished -> transit to the next
                S.seg = S.seg + 1; S.phase = "transit"; S.line, S.li = 1, 0
                return true
            end
        end
        local zoff = (S.line == 1) and -4 or 4
        local xs = (S.dir == -1) and (seg.x1 - S.li * RES) or (seg.x0 + S.li * RES)
        x, z = xs, seg.z + zoff
        S.tx, S.tz = x, z                        -- keep the transit cursor at the camera (no stale far-jumps)
    end
    local alt = S.guess + CLEAR

    pcall(Object.SetPosition, S.prop, x, alt, z)
    pcall(Ess.Camera.placeCamera, x, alt + CAM_UP, z, 0)
    local okh, h = pcall(Object.GetHeightAboveTerrain, S.prop)

    local advance = false
    local g = (okh and h and h > 2 and h < SENTINEL_H) and (alt - h) or nil
    if g and (g < -0.25 or g > 0.25) then
        S.guess = g; S.n = S.n + 1; S.retry, S.zeroStreak = 0, 0
        wsline(string.format("<<GROUND>>%.2f,%.2f,%.2f,%.2f", x, alt, z, h))
        advance = true
    elseif g then                                -- exact-0 = unstreamed: hold and wait (that's WHY it's a gap)
        S.retry = S.retry + 1
        local budget = (S.zeroStreak > 8) and 1 or ZERO_RETRY
        if S.retry > budget then S.retry = 0; S.zeroStreak = S.zeroStreak + 1; advance = true end
    else
        if h and h >= SENTINEL_H then S.guess = clamp(S.guess - SEARCH, GUESS_LO, GUESS_HI)
        else S.guess = clamp(S.guess + SEARCH, GUESS_LO, GUESS_HI) end
        S.retry = S.retry + 1
        if S.retry > MAX_RETRY then S.retry = 0; advance = true end
    end

    if advance then
        if S.phase == "transit" then
            local ex, dir = segEntry(seg)
            local dx, dz = ex - S.tx, seg.z - S.tz
            local d = math.sqrt(dx * dx + dz * dz)
            if d <= HOP then
                S.phase = "scan"; S.dir = dir; S.line, S.li, S.retry = 1, 0, 0
                S.tx, S.tz = ex, seg.z
                if S.seg % 25 == 1 then
                    Ess.Log(string.format("[gapstream] segment %d/%d (z=%d) -- %d pt(s) so far.", S.seg, #SEGS, seg.z, S.n))
                end
            else
                S.tx = S.tx + dx / d * HOP
                S.tz = S.tz + dz / d * HOP
            end
        else
            S.li = S.li + 1
        end
    end
    return true
end)
'''


if __name__ == "__main__":
    raise SystemExit(main())
