#!/usr/bin/env python3
"""build_terrain_lua.py -- bake the height tensor into an IN-GAME Lua module (ingame/Terrain.lua).

Why: the engine's Object.GetHeightAboveTerrain only answers for geometry that is STREAMED IN -- the whole
reason the camera-walk scan exists. This module gives game mods an offline oracle instead:

    local h = Terrain.heightAt(x, z)          -- ground height, or nil where never scanned
    Terrain.isWater(x, z)                     -- true below the -35 sea surface
    Terrain.groundY(x, z, fallback)           -- height + tiny clearance, or fallback where unknown
    Terrain.agl(x, y, z)                      -- height above ground for a world point (nil if unknown)

so spawns/airdrops/waypoints can be ground-snapped ANYWHERE without waiting for streaming. Ess is not
required, but if present the module also registers as Ess.Terrain.

Storage: heights quantised to 0.1u in TWO raw byte strings (low/high byte planes), embedded as \\ddd-escaped
Lua literals. Queries are two string.byte calls -- no decode pass, no bit library, Lua 5.1 safe. ~1 MB file,
~0.9 MB resident (the two strings).

Run:  python tools/build_terrain_lua.py    (after tools/build_heightmap.py)
"""
import json, base64, struct, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
HM_JS = ROOT / "src" / "data" / "heightmap.js"
OUT = ROOT / "ingame" / "Terrain.lua"

SENTINEL = -32768
SEA_LEVEL = -35.0
# unsigned cell encoding: q = height*10 + 32768 ; 65535 = "never scanned"
U_SENTINEL = 65535


def lua_escape(b):
    """bytes -> Lua string-literal body. Everything non-printable (plus quote/backslash) as 3-digit \\ddd."""
    out = []
    for ch in b:
        if 32 <= ch <= 126 and ch not in (34, 92):   # printable, not " or \
            out.append(chr(ch))
        else:
            out.append("\\%03d" % ch)
    return "".join(out)


def main():
    src = HM_JS.read_text(encoding="utf-8")
    data = json.loads(src[src.index('{"cell"'):src.rindex("}") + 1])
    cell, ox, oz, w, h = data["cell"], data["ox"], data["oz"], data["w"], data["h"]
    q = struct.unpack("<%dh" % (w * h), base64.b64decode(data["heightsB64"]))

    lo = bytearray(w * h)
    hi = bytearray(w * h)
    known = 0
    for i, v in enumerate(q):
        u = U_SENTINEL if v == SENTINEL else max(0, min(65534, v + 32768))
        if v != SENTINEL:
            known += 1
        lo[i] = u & 0xFF
        hi[i] = u >> 8

    def literal_chunks(raw, per_line=4000):
        return "\n".join('"%s"' % lua_escape(raw[i:i + per_line]) + (" .." if i + per_line < len(raw) else "")
                         for i in range(0, len(raw), per_line))

    lua = []
    lua.append("-- Terrain.lua -- GENERATED by mercs2-webmap tools/build_terrain_lua.py. Do not hand-edit.")
    lua.append("-- Offline ground-height oracle baked from the GroundStream scan tensor (%d/%d cells, %du grid)." % (known, w * h, cell))
    lua.append("-- Works WITHOUT streaming: Terrain.heightAt(x,z) answers anywhere that has been scanned.")
    lua.append("-- Standalone (no Ess needed); registers as Ess.Terrain too when Ess is present.")
    lua.append("")
    lua.append("local CELL, OX, OZ, W, H = %d, %d, %d, %d, %d" % (cell, ox, oz, w, h))
    lua.append("local SEA = %.1f" % SEA_LEVEL)
    lua.append("")
    lua.append("local LO =")
    lua.append(literal_chunks(bytes(lo)))
    lua.append("local HI =")
    lua.append(literal_chunks(bytes(hi)))
    lua.append("""
local floor, byte = math.floor, string.byte

local Terrain = { cell = CELL, sea = SEA, cols = W, rows = H }

-- raw cell height in world units, or nil where never scanned / off-grid
local function cellH(ix, iz)
    if ix < 0 or iz < 0 or ix >= W or iz >= H then return nil end
    local i = iz * W + ix + 1
    local u = byte(LO, i) + byte(HI, i) * 256
    if u == 65535 then return nil end
    return (u - 32768) / 10
end

-- ground height at a world point: exact cell, else best of the 8 neighbours (scan-edge tolerance). nil = unknown.
function Terrain.heightAt(x, z)
    local ix, iz = floor(x / CELL) - OX, floor(z / CELL) - OZ
    local h = cellH(ix, iz)
    if h then return h end
    local sw, sv = 0, 0
    for dz = -1, 1 do for dx = -1, 1 do
        local hh = cellH(ix + dx, iz + dz)
        if hh then local w2 = 1 / (dx * dx + dz * dz); sw = sw + w2; sv = sv + hh * w2 end
    end end
    if sw > 0 then return sv / sw end
    return nil
end

function Terrain.isWater(x, z)
    local h = Terrain.heightAt(x, z)
    return h ~= nil and h <= SEA
end

-- safe spawn/teleport y: ground + clearance on land, just above the surface over water, fallback where unscanned
function Terrain.groundY(x, z, fallback)
    local h = Terrain.heightAt(x, z)
    if not h then return fallback end
    if h <= SEA then return SEA + 2 end
    return h + 1
end

-- height above ground of a world point (negative = below the scanned mesh, e.g. under a bridge). nil = unknown.
function Terrain.agl(x, y, z)
    local h = Terrain.heightAt(x, z)
    if not h then return nil end
    return y - h
end

_G.Terrain = Terrain
if _G.Ess then _G.Ess.Terrain = Terrain end
if Loader and Loader.Printf then Loader.Printf("[terrain] oracle loaded: LOADMSG") end
return Terrain""".replace("LOADMSG", "%d x %d cells @ %du" % (w, h, cell)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lua) + "\n", encoding="ascii")

    # round-trip verification: re-parse the emitted literals and compare every cell against the tensor
    text = OUT.read_text(encoding="ascii")
    def parse_plane(marker):
        i = text.index(marker) + len(marker)
        out = bytearray()
        j = i
        while True:
            j = text.index('"', j) + 1
            while text[j] != '"':
                if text[j] == "\\":
                    out.append(int(text[j + 1:j + 4])); j += 4
                else:
                    out.append(ord(text[j])); j += 1
            j += 1
            k = text.find("..", j, j + 4)
            if k == -1:
                break
            j = k + 2
        return bytes(out)
    rlo, rhi = parse_plane("local LO ="), parse_plane("local HI =")
    assert len(rlo) == w * h and len(rhi) == w * h, "plane length mismatch"
    for i, v in enumerate(q):
        u = rlo[i] + rhi[i] * 256
        expect = U_SENTINEL if v == SENTINEL else max(0, min(65534, v + 32768))
        assert u == expect, "cell %d mismatch" % i
    kb = OUT.stat().st_size // 1024
    print("[terrain.lua] %d/%d cells baked -> %s (%d KB) -- round-trip verified OK" % (known, w * h, OUT, kb))


if __name__ == "__main__":
    raise SystemExit(main())
