#!/usr/bin/env python3
"""build_heightmap.py -- turn driven/walked position logs into a coarse height grid for the webmap.

Reads every data/*.log, pulls out `x= y= z=` samples (y = height -- works for [ROAD] drive logs AND
[LOCATION] "standing here" captures), and bins them to a grid: each occupied cell stores the MEDIAN height
of the samples that fell in it, plus the sample count. Median (not mean) shrugs off outliers like the
spawn-settle point at the start of a drive, and re-driving/re-walking a spot only sharpens the estimate.

Coverage grows over time -- just drop more logs in data/ and re-run. Output is src/data/heightmap.js:
  window.MERCS_HEIGHTMAP = { cell, cells: { "cx,cz": [medianHeight, sampleCount] }, yMin, yMax, n, ... }
Cells are integer grid coords: cx = floor(x / cell), cz = floor(z / cell) (the JS side uses the same).

Run:  python tools/build_heightmap.py [--cell 32]
"""
import re, glob, json, math, statistics, pathlib, argparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOGS_DIR = ROOT / "data"
OUT = ROOT / "src" / "data" / "heightmap.js"
# tolerant: matches "x=.. y=.. z=.." anywhere on a line (ROAD, LOCATION, or any future tagged pose line)
RX = re.compile(r"x=(-?[\d.]+)\s+y=(-?[\d.]+)\s+z=(-?[\d.]+)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", type=int, default=32, help="grid cell size in world units")
    args = ap.parse_args()
    cell = max(1, args.cell)

    buckets = {}   # (cx, cz) -> [y, ...]
    files = sorted(glob.glob(str(LOGS_DIR / "*.log")))
    for f in files:
        for line in open(f, encoding="utf-8", errors="ignore"):
            m = RX.search(line)
            if not m:
                continue
            x, y, z = float(m.group(1)), float(m.group(2)), float(m.group(3))
            buckets.setdefault((math.floor(x / cell), math.floor(z / cell)), []).append(y)

    if not buckets:
        raise SystemExit("no x=/y=/z= samples found in %s/*.log" % LOGS_DIR)

    cells, heights = {}, []
    for (cx, cz), vals in buckets.items():
        h = statistics.median(vals)
        cells["%d,%d" % (cx, cz)] = [round(h, 2), len(vals)]
        heights.append(h)

    n = sum(len(v) for v in buckets.values())
    data = {
        "cell": cell,
        "cells": cells,
        "yMin": round(min(heights), 2),
        "yMax": round(max(heights), 2),
        "n": n,
        "cellCount": len(cells),
        "logs": [pathlib.Path(f).name for f in files],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by tools/build_heightmap.py from data/*.log -- do not hand-edit.\n"
        "// Coarse height grid: cell=%d world-units; each cell = [median height, sample count].\n"
        "// Grows as you add logs. cx=floor(x/cell), cz=floor(z/cell).\n"
        "window.MERCS_HEIGHTMAP = %s;\n" % (cell, json.dumps(data, separators=(",", ":"))),
        encoding="utf-8")
    print("[heightmap] %d samples -> %d cells (cell=%d), y %.1f..%.1f, from %d log(s): %s"
          % (n, len(cells), cell, data["yMin"], data["yMax"], len(files), ", ".join(data["logs"])))


if __name__ == "__main__":
    raise SystemExit(main())
