#!/usr/bin/env python3
"""build_heightmap.py -- turn driven/walked position logs into a coarse height grid for the webmap.

Reads every data/*.log, pulls out `x= y= z=` samples (y = height -- works for [ROAD] drive logs AND
[LOCATION] "standing here" captures), and bins them to a grid: each occupied cell stores the MEDIAN height
of the samples that fell in it, plus the sample count. Median (not mean) shrugs off outliers like the
spawn-settle point at the start of a drive, and re-driving/re-walking a spot only sharpens the estimate.

Coverage grows over time -- just drop more logs in data/ and re-run. Output is src/data/heightmap.js:
  window.MERCS_HEIGHTMAP = { cell, cells: { "cx,cz": [medianHeight, sampleCount] }, yMin, yMax, n, ... }
Cells are integer grid coords: cx = floor(x / cell), cz = floor(z / cell) (the JS side uses the same).

Run:  python tools/build_heightmap.py [--cell 32]
"""
import re, glob, json, math, statistics, pathlib, argparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOGS_DIR = ROOT / "data"
OUT = ROOT / "src" / "data" / "heightmap.js"
# tolerant: matches "x=.. y=.. z=.." anywhere on a line (ROAD, LOCATION, or any future tagged pose line)
RX = re.compile(r"x=(-?[\d.]+)\s+y=(-?[\d.]+)\s+z=(-?[\d.]+)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", type=int, default=32, help="grid cell size in world units")
    ap.add_argument("--ymin", type=float, default=-100.0, help="drop samples below this y (fell through the world)")
    ap.add_argument("--ymax", type=float, default=250.0, help="drop samples above this y (real terrain/roofs are < ~71)")
    args = ap.parse_args()
    cell = max(1, args.cell)

    # The PMC HQ interior is an off-map instanced pocket near (x 3794, z -3911) at y ~450 -- exiting drops you
    # somewhere else entirely (~2558,-13,-924). Any sample inside it is a fake corner spike, so drop high-y
    # samples in that corner. (The generic --ymax also catches it; this is the precise regional guard.)
    def keep(x, y, z):
        if y < args.ymin or y > args.ymax:
            return False
        if y > 150 and math.hypot(x - 3794.0, z - (-3911.0)) < 500.0:   # HQ interior instance
            return False
        return True

    # source authority -- when sources disagree in a cell, the more trustworthy one wins the height:
    # vehicle (on the road) > foot (standing, but could be mid-jump) > grid probe (may stack / land on a roof).
    TIER = {"vehicle": 3, "foot": 2, "grid": 1}
    def source(line):
        if "[ROAD]" in line: return "vehicle"
        if "[FOOT]" in line or "[LOCATION]" in line: return "foot"
        return "grid"   # [GRID] and anything unrecognised -> lowest authority

    buckets, dropped = {}, 0   # (cx, cz) -> { tier: [y, ...] }
    files = sorted(glob.glob(str(LOGS_DIR / "*.log")))
    for f in files:
        for line in open(f, encoding="utf-8", errors="ignore"):
            m = RX.search(line)
            if not m:
                continue
            x, y, z = float(m.group(1)), float(m.group(2)), float(m.group(3))
            if not keep(x, y, z):
                dropped += 1
                continue
            key = (math.floor(x / cell), math.floor(z / cell))
            buckets.setdefault(key, {}).setdefault(source(line), []).append(y)

    if not buckets:
        raise SystemExit("no x=/y=/z= samples found in %s/*.log" % LOGS_DIR)

    cells, heights = {}, []
    for (cx, cz), bytier in buckets.items():
        best = max(bytier, key=lambda t: TIER[t])      # highest-authority source present in this cell
        h = statistics.median(bytier[best])            # median WITHIN that source only (lower tiers don't dilute it)
        total = sum(len(v) for v in bytier.values())
        cells["%d,%d" % (cx, cz)] = [round(h, 2), total, TIER[best]]
        heights.append(h)

    n = sum(len(v) for bt in buckets.values() for v in bt.values())
    data = {
        "cell": cell,
        "cells": cells,
        "yMin": round(min(heights), 2),
        "yMax": round(max(heights), 2),
        "n": n,
        "cellCount": len(cells),
        "logs": [pathlib.Path(f).name for f in files],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by tools/build_heightmap.py from data/*.log -- do not hand-edit.\n"
        "// Coarse height grid: cell=%d world-units; each cell = [median height, sample count, source tier].\n"
        "// source tier: 3=vehicle(road) 2=foot 1=grid-probe -- the highest-authority source present wins the cell.\n"
        "// Grows as you add logs. cx=floor(x/cell), cz=floor(z/cell).\n"
        "window.MERCS_HEIGHTMAP = %s;\n" % (cell, json.dumps(data, separators=(",", ":"))),
        encoding="utf-8")
    print("[heightmap] %d samples -> %d cells (cell=%d), y %.1f..%.1f, from %d log(s): %s"
          % (n, len(cells), cell, data["yMin"], data["yMax"], len(files), ", ".join(data["logs"])))
    if dropped:
        print("[heightmap] dropped %d out-of-range sample(s) (HQ interior / fell-through / y<%.0f or y>%.0f)"
              % (dropped, args.ymin, args.ymax))


if __name__ == "__main__":
    raise SystemExit(main())
