#!/usr/bin/env python3
"""gen_map_image.py -- downscale the 8204x8204 game map into an embeddable data: URI.

The webmap is a SINGLE standalone HTML (like the Ess/IDE builds), so the map picture has to live INSIDE
it. The retail map.jpg is 8204x8204 / ~5.5 MB -- far too big to base64-inline. But the coordinate space is
LOGICAL (Leaflet's CRS.Simple bounds are the 8204-unit world span, independent of the image's real pixel
size), so we can shrink the picture as much as we like without touching the calibration: Leaflet just
stretches whatever image we give it across the same bounds. This writes src/data/map-image.js which sets
window.MERCS_MAP_IMAGE to a `data:image/jpeg;base64,...` URI.

Run it once (or when you want to retune size/quality):  python tools/gen_map_image.py [--size 4096] [--quality 82]
The source map.jpg lives in the sibling mercs2-tools repo; override with --src if it moved.
"""
import argparse, base64, io, pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT.parent / "mercs2-tools" / "map.jpg"
OUT = ROOT / "src" / "data" / "map-image.js"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=str(DEFAULT_SRC), help="source map.jpg")
    ap.add_argument("--size", type=int, default=4096, help="downscaled square edge in px")
    ap.add_argument("--quality", type=int, default=82, help="JPEG quality 1-95")
    args = ap.parse_args()

    src = pathlib.Path(args.src)
    if not src.exists():
        raise SystemExit("map source not found: %s (pass --src)" % src)

    im = Image.open(src).convert("RGB")
    ow, oh = im.size
    if args.size and args.size < max(ow, oh):
        im = im.resize((args.size, args.size), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=args.quality, optimize=True, progressive=True)
    raw = buf.getvalue()
    uri = "data:image/jpeg;base64," + base64.b64encode(raw).decode("ascii")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    header = ("// GENERATED by tools/gen_map_image.py -- do not hand-edit.\n"
              "// source %s (%dx%d) downscaled to %dx%d q%d = %d KB jpeg.\n"
              % (src.name, ow, oh, im.size[0], im.size[1], args.quality, len(raw) // 1024))
    OUT.write_text(header + "window.MERCS_MAP_IMAGE = %r;\n" % uri, encoding="utf-8")
    print("[map] %s  (%d KB jpeg -> %d KB base64 in %s)" % (
        "%dx%d q%d" % (im.size[0], im.size[1], args.quality), len(raw) // 1024, len(uri) // 1024, OUT.name))


if __name__ == "__main__":
    raise SystemExit(main())
